# Generated by Django 5.0.1 on 2024-02-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0001_initial'),
        ('Vaccine', '0004_alter_vaccine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='vaccine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vaccine.vaccine'),
        ),
    ]
