# Generated by Django 5.0.1 on 2024-02-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nid',
            field=models.IntegerField(),
        ),
    ]
