# Generated by Django 5.0.1 on 2024-02-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_nid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
