# Generated by Django 5.0.1 on 2024-02-27 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vaccine', '0009_alter_vaccine_initiated_date_delete_vaccinerecord'),
        ('user', '0009_alter_doctormodel_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.patientmodel')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vaccine.vaccine')),
            ],
        ),
    ]
