# Generated by Django 5.0.1 on 2024-02-27 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinerecord',
            name='date_taken',
            field=models.DateField(default=datetime.datetime(2024, 2, 27, 16, 45, 6, 183836, tzinfo=datetime.timezone.utc)),
        ),
    ]
