# Generated by Django 5.0.1 on 2024-03-01 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_history', '0002_alter_vaccinerecord_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinerecord',
            name='date_taken',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
