# Generated by Django 5.0.1 on 2024-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='schedule',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='dose_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('complete', 'complete'), ('continuous', 'continuous')], default=3, max_length=10),
            preserve_default=False,
        ),
    ]
