# Generated by Django 5.0.1 on 2024-02-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0002_remove_vaccine_schedule_vaccine_dose_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='dose_count',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
