# Generated by Django 5.0.1 on 2024-02-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0003_alter_vaccine_dose_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
