# Generated by Django 5.0.1 on 2024-02-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0004_alter_vaccine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='vaccine/images/'),
        ),
    ]
