# Generated by Django 5.0.1 on 2024-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0006_vaccine_campaign_name_vaccine_initiated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='campaign_name',
            field=models.CharField(blank=True, default='null', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='initiated_date',
            field=models.DateTimeField(blank=True, default='2024-02-23', null=True),
        ),
    ]
