# Generated by Django 5.0.1 on 2024-02-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0008_vaccinerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='initiated_date',
            field=models.DateTimeField(blank=True, default='2024-02-27', null=True),
        ),
        migrations.DeleteModel(
            name='VaccineRecord',
        ),
    ]
