# Generated by Django 5.0.1 on 2024-03-01 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0009_alter_vaccine_initiated_date_delete_vaccinerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='initiated_date',
        ),
    ]
