# Generated by Django 5.0.1 on 2024-03-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0010_remove_vaccine_initiated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='first_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='second_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
