# Generated by Django 5.0.1 on 2024-03-04 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0011_vaccine_first_dose_date_vaccine_second_dose_date'),
        ('user', '0009_alter_doctormodel_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_name', to='user.patientmodel')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_name', to='Vaccine.vaccine')),
            ],
        ),
    ]
