# Generated by Django 5.0.1 on 2024-02-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usermodel_past_medical_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='user.usermodel'),
        ),
    ]
