# Generated by Django 5.0.1 on 2024-02-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0001_initial'),
        ('user', '0003_alter_patientmodel_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='user.usermodel')),
                ('vaccines', models.ManyToManyField(related_name='vaccines', to='Vaccine.vaccine')),
            ],
        ),
    ]
