# Generated by Django 5.0.1 on 2024-02-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0001_initial'),
        ('user', '0005_alter_doctormodel_vaccines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='vaccines',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='campaign',
            field=models.ManyToManyField(related_name='campaign', to='Campaign.campaign'),
        ),
    ]
