# Generated by Django 5.0.1 on 2024-02-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_usermodel_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctormodel',
            name='campaign',
        ),
    ]
