# Generated by Django 5.0.1 on 2024-02-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_doctormodel_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.usermodel'),
        ),
    ]
